Storefront profile fix, Toast color
BrainStation-23/BS-Commerce pull request #317
Opened 2022-08-03 05:01 UTC by sakibbye

# Description

(Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.)

## Type of change

(Please delete options that are not relevant.)

- [ ] Link to a **GH Issue** or **Jira** task here for reference.
- [ ] Bug fix
- [ ] New feature

# How Has This Been Tested?

(Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration)

- [ ] Tested by myself
- [ ] Unit test

# Developer Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Review check list:

- [ ] Separation of Concerns followed (Reviewer name/NaN)
- [ ] Code is in sync with existing code patterns/technologies. (Reviewer name/NaN)
- [ ] Are there any obvious optimizations that will improve performance? (Reviewer name/NaN)
- [ ] Can any logging or debugging code be removed? (Reviewer name/NaN)
- [ ] Are all data inputs checked (for the correct type, length, format, and range) and encoded? (Reviewer name/NaN)
- [ ] Are invalid parameter values handled? (Reviewer name/NaN)
- [ ] Is error handling done the correct way? (Reviewer name/NaN)
- [ ] Are all the edge cases (null, 0, negative) handled properly? (Reviewer name/NaN)

2022-08-03 05:03 UTC, sakibbye commented
https://pm23.atlassian.net/browse/BC-433
https://pm23.atlassian.net/browse/BC-431
https://pm23.atlassian.net/browse/BC-460

2022-08-04 05:42 UTC, asaduzzamanbs23 commented on packages/storefront/components/myAccount/account-details.tsx
> +var cookie = require('cookie');
@sakibbye why you need cookie here

2022-08-04 05:43 UTC, asaduzzamanbs23 commented on packages/storefront/components/myAccount/account-details.tsx
> +
@sakibbye remove unusual line

2022-08-04 05:46 UTC, asaduzzamanbs23 commented on packages/storefront/components/myAccount/account-details.tsx
> +var cookie = require('cookie');
@sakibbye why you need cookie here

2022-08-04 05:48 UTC, asaduzzamanbs23 requested changes
@sakibbye 
1. Remove unusual line
2. Remove unusual import

2022-08-04 05:55 UTC, sakibbye commented
@asaduzzamanbs23 changes done bhai

2022-08-04 08:10 UTC, asaduzzamanbs23 approved these changes

2022-08-04 08:15 UTC, merged